import { useState } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { ArrowRight, Heart, LockKeyhole } from 'lucide-react';
import { useAuth } from '../context/AuthContext';

export function AuthPage({ mode }) {
  const isRegister = mode === 'register'; const { login, register } = useAuth(); const navigate = useNavigate(); const location = useLocation();
  const [form, setForm] = useState({ displayName: '', username: '', email: '', password: '' }); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const update = (event) => setForm({ ...form, [event.target.name]: event.target.value });
  async function submit(event) { event.preventDefault(); setError(''); setBusy(true); try { await (isRegister ? register(form) : login({ email: form.email, password: form.password })); navigate(location.state?.from || '/chat'); } catch (err) { setError(err.message); } finally { setBusy(false); } }
  return <main className="auth-page"><section className="auth-copy"><div className="brand-mark">o</div><p className="eyebrow">A private room for your people</p><h1>OURS<span>.</span></h1><p className="tagline">A little place for us.</p><div className="memory-note"><Heart size={15} fill="currentColor" /> small circles. soft landings. good stories.</div></section><section className="auth-card"><div className="auth-card-top"><div><p className="eyebrow">{isRegister ? 'Make some room' : 'Welcome back'}</p><h2>{isRegister ? 'Find your way in.' : 'Pick up where you left off.'}</h2></div><LockKeyhole size={20} /></div><form onSubmit={submit}>{isRegister && <><label>Display name<input name="displayName" value={form.displayName} onChange={update} placeholder="Sarjanaa" required /></label><label>Username<input name="username" value={form.username} onChange={update} placeholder="sarjanaa" required /></label></>}<label>Email<input name="email" type="email" value={form.email} onChange={update} placeholder="you@example.com" required /></label><label>Password<input name="password" type="password" value={form.password} onChange={update} placeholder="8 characters minimum" minLength="8" required /></label>{error && <p className="form-error">{error}</p>}<button className="primary-button" disabled={busy}>{busy ? 'Opening...' : isRegister ? 'Create my room' : 'Enter OURS'} <ArrowRight size={17} /></button></form><p className="auth-switch">{isRegister ? 'Already have a room?' : 'New around here?'} <Link to={isRegister ? '/login' : '/register'}>{isRegister ? 'Log in' : 'Create an account'}</Link></p></section></main>;
}
