import { useState } from 'react';
import { Bell, ChevronRight, Compass, LogOut, MessageCircle, Plus, Search, Users } from 'lucide-react';
import { motion } from 'framer-motion';
import { useAuth } from '../context/AuthContext';

export default function Sidebar({ conversations, selectedId, onSelect, onNew, onNewGroup, onProfile, onNotifications, notifications = 0 }) {
  const { user, logout } = useAuth();
  const [query, setQuery] = useState('');
  const visibleConversations = conversations.filter((conversation) => { const other = conversation.members.find((member) => String(member._id) !== String(user.id)); const haystack = `${conversation.name || ''} ${other?.displayName || ''} ${other?.username || ''}`.toLowerCase(); return haystack.includes(query.toLowerCase()); });
  return <aside className="sidebar"><div className="sidebar-brand"><div className="brand-mark small">o</div><div><strong>OURS</strong><small>a little place for us</small></div><button className="icon-button mobile-only" onClick={onProfile}><ChevronRight size={18} /></button></div><div className="search-box"><Search size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Find a conversation..." /></div><nav className="nav-links"><button className="active"><MessageCircle size={18} /> Conversations <span>{conversations.length}</span></button><button onClick={onNew}><Users size={18} /> Friends <Plus size={15} /></button><button onClick={onNewGroup}><Compass size={18} /> Groups <Plus size={15} /></button></nav><div className="conversation-heading"><span>Recent rooms</span><button onClick={onNew}><Plus size={17} /></button></div><div className="conversation-list">{visibleConversations.length ? visibleConversations.map((conversation) => { const other = conversation.members.find((member) => String(member._id) !== String(user.id)) || conversation.members[0]; return <motion.button layout key={conversation._id} className={`conversation-item ${selectedId === conversation._id ? 'selected' : ''}`} onClick={() => onSelect(conversation)}><div className="avatar-wrap"><Avatar person={conversation.isGroup ? { displayName: conversation.name, profileImage: conversation.groupImage } : other} /><i className={other?.isOnline ? 'online-dot' : ''} /></div><div className="conversation-meta"><strong>{conversation.isGroup ? conversation.name : other?.displayName}</strong><span>{conversation.lastMessage?.text || 'Start something worth remembering.'}</span></div><time>{conversation.lastMessage ? new Date(conversation.lastMessage.createdAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) : ''}</time></motion.button> }) : <div className="empty-list">{query ? 'No one here yet.' : 'Your little corner of the internet is waiting. 🫶'}</div>}</div><div className="sidebar-bottom"><button className="profile-row" onClick={onProfile}><Avatar person={user} /><span><strong>{user.displayName}</strong><small>@{user.username}</small></span><ChevronRight size={16} /></button><button className="logout-button" onClick={logout}><LogOut size={16} /> Log out</button><button className="notification-button" onClick={onNotifications}><Bell size={17} />{notifications > 0 && <b>{notifications}</b>}</button></div></aside>;
}
export function Avatar({ person = {}, large = false }) { return person?.profileImage ? <img className={`avatar ${large ? 'large' : ''}`} src={person.profileImage} alt="" /> : <div className={`avatar avatar-fallback ${large ? 'large' : ''}`}>{(person?.displayName || person?.username || '?').slice(0, 1).toUpperCase()}</div>; }
